version: '3.1'
services:
  unit_php:
    image: michelsp/php:oci-8.2
    container_name: unit_php
    volumes:
      - .:/var/www/webdev
      - ./docker/php7-fpm/fpm.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
      - ./docker/php7-fpm/cli.ini:/etc/php/7.1/cli/conf.d/99-overrides.ini

  unit_http:
    image: nginx:latest
    container_name: unit_http
    environment:
      - HOSTNAME=unit
      - VIRTUAL_HOST=unit
      - VIRTUAL_PORT=8080
    volumes:
      - .:/var/www/webdev
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    links:
      - unit_php

